# Generated by Django 2.0 on 2017-12-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lc',
            options={'verbose_name_plural': 'LC'},
        ),
        migrations.RenameField(
            model_name='lcitem',
            old_name='dlv',
            new_name='yarn_dlv',
        ),
        migrations.RenameField(
            model_name='lcitem',
            old_name='rcv',
            new_name='yarn_rcv',
        ),
        migrations.AddField(
            model_name='lcitem',
            name='yarn_bal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
