# Generated by Django 2.0 on 2017-12-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_auto_20171208_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lcitem',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lcitem',
            name='style_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
