# Generated by Django 2.0 on 2017-12-10 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0003_auto_20171209_0934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lcitem',
            old_name='style_no',
            new_name='style',
        ),
    ]
