# Generated by Django 2.0 on 2017-12-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20171210_0713'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yarnrcv',
            options={'verbose_name_plural': 'Yarn Rcv'},
        ),
    ]
